# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'maven-examples/pom.xml'
    goals: 'deploy'
    artifactoryResolverService: 'demo'
    targetResolveReleaseRepo: 'team1-libs-release'
    targetResolveSnapshotRepo: 'team1-libs-snapshot'
    artifactoryDeployService: 'demo'
    targetDeployReleaseRepo: 'team1-libs-release-local'
    targetDeploySnapshotRepo: 'team1-libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
    includeEnvVars: true
    projectKey: 'alpha'


- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'demo'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'devops'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'demo-xray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: true
    projectKey: 'alpha'

    